### ISSUE TITLE
GiveUp: Request a obfs4 server

### ISSUE THREAD

**Issue by mhtvsSFrpHdE** [tako774/tsk_report#5]
```
Removed
```

**Comment by tako774** [comment]
From my understanding,
1. Using HTTP, ISP cache/drop data problem occurs.
2. Using obfs4 with obfs4 server in California, RTT is more than 380msec, so 'few user' can not upload.

My questions are
1. Is it really true that too high RTT causes the upload problem?
2. Does HTTPS solves both problems?

I don't understand how to operate obfs4 server, especially about security perspective, so currently I feel not for building obfs4 server. If I do so, at least I'll make another virtual machine for it.
If HTTPS solves the problem, to change client is better.

By the way, I want to make discussion here rather than Email, I want discuss in open place.

**Comment by Incubator85653** [comment]
@tako774 I'm not to force you taking with me via email, sorry. I mean we may need to exchange something like... if I should give you my server cert or password, that private information.

HTTPS solves the problem of course.
But the question is if we use obfs4 server,  obfs4 is good to set up the proxy server. Very few users couldn't even access original tenco server. They need the proxy server. If we write hosts file(SNA proxy) or set cname record(port forwarding) to set up Transparent Proxy, HTTPS will warn the user that cert error.

In another hand, I can't write Ruby code. So if you ask me to turn the client protocol as HTTPS, I can't do that.

**What exactly is obfs4?**

https://www.torproject.org/docs/pluggable-transports.html.en

obfs4 is a traffic confusion tool developed by TOR project, TOR is very well-known anonymous network services. They're open source.
At least I trust their codes... I think so.
In many countries, the government tries to block TOR. In order to prevent being blocked they starting a plan, hide their protocol characteristics. From history, they developed "Flashproxy", "obfs2", "obfs3", "ScrambleSuit", lots of tools. The latest tool called "obfs4". Lots of information shows obfs4 is very valid.

TOR is an open source software. So we can use their codes to do our self-things. An example is, in China, people like use "Shadowsocks" to bypass government blockade. This protocol is valid in the early stage. After few years, the government knows how to stop people using this protocol. And now, someone of us run "Shadowsocks" through obfs4 tool.

In this situation, obfs4 convert "Shadowsocks" protocol as obfs4 self-protocol and send them to internet. We call obfs4 as a tool, because not just TOR or Shadowsocks, obfs4 can make any TCP protocol into it self-protocol(port forwarding). The HTTP protocol can turn to obfs4 of course. After that, evil ISP couldn't detect HTTP request or make a cache for them anymore.

To use obfs4 tool for our tenco service, we need another tool called "ptproxy". We already know obfs4 originally as a part of TOR project, how to export the powerful abilities to help us? --ptproxy.

**And what is ptproxy?**

ptproxy is a helper to use obfs4 for any traffic.
imagine, you got an axe, but without a handle. ptproxy is the handle you want. The most important thing is -- ptproxy is also an open source software.

https://github.com/gumblex/ptproxy

**Why obfs4 but not HTTPS?**
HTTPS is powerful, but not flexible enough. if we add HTTPS to tsk_report, is very hard to add proxy server ability to it at the same time. The codes need huge modify. I can't write Ruby code, you may don't have enough time to do it, and after we truly use HTTPS, we will meet the old problem: "Very lots of proxy protocol are blocked in China".
So, I think, use obfs4 will be better than HTTPS for both of us.
To set up a proxy server for obfs4 protocol we just simply forward port, from any IP address. obfs4 don't need CA like HTTPS, it uses pre-set key string to verify client and server identity.

**How to set up obfs4 server?**

I'll answer the full tutorial if you agree to set up this protocol.
For my design, all server should use the same configuration so if one of the servers is down, modify the DNS A record could switch to another server. --That's why I asked email discuss.
